name: Deployment

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions: {}
jobs:
  deploy:
    permissions:
      contents: write # for release creation (svenstaro/upload-release-action)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Apply Patch
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions"
        cd work && ../scripts/applyPatches.sh

    - name: Create artifacts
      run: |
        cd ./work
        ./gradlew -Pbuildversion=${RELEASE_VERSION:1} server:dist
    - name: Upload server artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: work/server/build/libs/server-release.jar
        tag: ${{ github.ref }}

